package com.example.gossipwars.map.src

enum class Province {
    Alborz,
    Kerman,
    SistanAndBaluchestan,
    NorthKhorasan,
    RazaviKhorasan,
    SouthKhorasan,
    Kordestan,
    Gilan,
    Kermanshah,
    EastAzarbaijan,
    WestAzarbaijan,
    Qazvin,
    Zanjan,
    Hamadan,
    Qom,
    Markazi,
    Ardebil,
    Hormozgan,
    Ilam,
    Lorestan,
    Khuzestan,
    ChaharMahallAndBakhtiari,
    Yazd,
    Tehran,
    Semnan,
    Mazandaran,
    Golestan,
    Fars,
    Esfahan,
    Bushehr,
    KohgiluyehAndBoyerAhmad
}